### ISSUE TITLE
Dockerize Arduino Build Environment

### ISSUE THREAD

**Issue by CalebProvost** [AESD-Course-Project/AESD-Course-Project.github.io#12]
DoD: Dockerfile will initially build the demo app for the Arduino. End user performs Docker command to build and run, it will compile and flash the Arduino with the demo.

**Comment by arpit6232** [comment]
Successfully created Dockerfile to Compile and upload person detection Code from x86 to 33 Nano BLE Arduino. 

DoD's done: 
Source : https://github.com/cu-ecen-5013/final-project-arpit6232/tree/main/docker_arduino
Docker Image : https://hub.docker.com/repository/docker/arpit6232/arduino_cli
Library Created: https://github.com/arpit6232/arduino-library/tree/01df1180b684219de3d97944c1b0964f816356ee
