### ISSUE TITLE
Arduino Project Code in Docker

### ISSUE THREAD

**Issue by CalebProvost** [AESD-Course-Project/AESD-Course-Project.github.io#13]
Continuation of issue https://github.com/AESD-Course-Project/AESD-Course-Project.github.io/issues/12.  
DoD: Modify Arduino Dockerfile to perform the previous action, but with our communication code instead.

**Comment by arpit6232** [comment]
@CalebProvost Ive tested this Dockerfile (https://github.com/cu-ecen-5013/final-project-arpit6232/tree/main/docker_arduino) to work with the Arduino 33 BLE . Should we integrate this.

**Comment by CalebProvost** [comment]
Closing as there was apparently confusion on assignments and was performed independently:  
https://github.com/AESD-Course-Project/AESD-Course-Project.github.io/issues/12#issuecomment-815348903  

**_Update_**: Prior work performed does not meet the agreed upon requirements. The following is re-work which meets the team's agreed upon requirements which can fit into the end goal specifications:  

- [x] Docker image which provides "arduino-cli": https://github.com/CalebProvost/dockter-arduino-cli/blob/master/Dockerfile  
- [x] Implementation of prior, which is used for our end-goal requirements: https://github.com/cu-ecen-5013/final-project-CalebProvost/blob/dard/Dockerfile

---

## Clarification to readers:  
1. The use of the docker images is so that each individual who wishes to build a portion of our project can do so with the **_exact same environment_**, thereby providing them the same results.  
2. These docker images are to be tools which the team has created for communities to freely use for their own purposes.  
3. **Our Team** then uses these tools **for our project**. This means we add &/or implement the functionality of our created tools to build our project.
