### ISSUE TITLE
Create Project's Yocto Layer

### ISSUE THREAD

**Issue by arpit6232** [AESD-Course-Project/AESD-Course-Project.github.io#15]
DoD: Create and add yocto layer and recipes; Update Dockerfile to automatically include it.

**Comment by CalebProvost** [comment]
Testing takes a while... Initial build successfully added the layer to the end image using our Docker container.   
However, contamination of the install segment required a fresh build. The latest Dockerfile implementations will (hopefully... see issue https://github.com/AESD-Course-Project/AESD-Course-Project.github.io/issues/10) resolve this issue.   

The following is the created layer which includes the project uartserver into end image.
https://github.com/cu-ecen-5013/final-project-CalebProvost/blob/yocto-layer/recipes-final-project/final-project/final-project.bb  

Test results: Blocker Encountered. Unknown reason as of yet. But the end-result SD Card image creation fails:  
```shell
[   0.1839 ] Updating BFS information on BCT
[   0.1866 ] tegrabct --bct jetson-nano-2gb-devkit.bct --chip 0x21 0 --updatebfsinfo flash.xml.bin
[   0.1888 ] 
[   0.1890 ] Copying signed file in /home/user/tegraflash/signed
Init...ERR: could not initialize GPT on /home/user/demo-image-full-jetson-nano-2gb-devkit.img
```

Will open an issue for resolving this for Sprint 3.
