### ISSUE TITLE
Incorporate GPIO signal to UART server

### ISSUE THREAD

**Issue by ZachTurner07** [AESD-Course-Project/AESD-Course-Project.github.io#20]
DoD: Whenever the message from the Arduino indicates a person was detected, an LED should be flashed with a GPIO signal.

- [ ] include GPIO write to UART server
- [ ] write to GPIO when message from Arduino indicates "true"

**Comment by ZachTurner07** [comment]
Pushed to demo if time permits, will cycle back to discuss with @arpit6232

**Comment by ZachTurner07** [comment]
closing as future work to be done as an improvement on this project

**Comment by arpit6232** [comment]
Removing the TODO tag. For completeness.
