### ISSUE TITLE
API , Setup and Response. 

### ISSUE THREAD

**Issue by arpit6232** [AESD-Course-Project/AESD-Course-Project.github.io#24]
DoD : Create an API between Jetson Nano and response from the Arduino BLE 33 Sense. 

Blockers: Testing, Arduino State machine response time to ARDUINO CLI.

**Comment by arpit6232** [comment]
As per @ZachTurner07 , 
UML Looks like this : 
![image](https://user-images.githubusercontent.com/55374040/114886875-2d5b2c00-9dc5-11eb-9a9e-b8660942228f.png)

**Comment by arpit6232** [comment]
Tested over Host for API send and response to the Arduino BLE 33 Sense , 

Commit : [a84a54d1917d7df28d2f5b73ebd9d51594dba393](https://github.com/arpit6232/arduino-library)

- Prerequisites
```
sudo stty -F /dev/ttyACM0 cs8 9600 ignbrk -brkint -icrnl -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts

sudo chmod 777 /dev/ttyACM0
``` 

- Work Output

- ![image](https://user-images.githubusercontent.com/55374040/115064254-f579e480-9ea9-11eb-9918-7059b989d1f7.png)

- ![image](https://user-images.githubusercontent.com/55374040/115064324-075b8780-9eaa-11eb-9ffc-6f08d71ff861.png)

- 
![image](https://user-images.githubusercontent.com/55374040/115084866-b27a3a00-9ec6-11eb-974e-9f2a0e0b25f7.png)

**Comment by arpit6232** [comment]
Tested the above Functionality on Jetson Nano, Arduino BLE reacts correctly.

**Comment by ZachTurner07** [comment]
Going to integrate this testing with UART server to validate integration

**Comment by ZachTurner07** [comment]
Trying to get the API to work with the user application

**Comment by ZachTurner07** [comment]
Simplifying API from words to single bytes simplified the implementation. Also, bytes are echoed back instead of responding with a different message to confirm it was detected.

**Comment by ZachTurner07** [comment]
commit [b78b2e5604f8d9c093e8094058d9f11884ed6531](https://github.com/cu-ecen-5013/final-project-ZachTurner07/commit/b78b2e5604f8d9c093e8094058d9f11884ed6531) establishes 2-way communication

**Comment by ZachTurner07** [comment]
Jetson Nano can send a serial command to the Arduino to command it to start
