### ISSUE TITLE
Integrate yocto package for arduino_cli to meta-final-project

### ISSUE THREAD

**Issue by arpit6232** [AESD-Course-Project/AESD-Course-Project.github.io#26]
DoD: Integrate PR for [arduino_cli](https://github.com/cu-ecen-5013/final-project-CalebProvost/tree/arduino_cli_package) into [yocto-layer](https://github.com/cu-ecen-5013/final-project-CalebProvost/tree/yocto-layer)

Blocker: 
![image](https://user-images.githubusercontent.com/55374040/115166042-5c47fb00-a06e-11eb-982f-0b1bf5c31546.png)

**Comment by arpit6232** [comment]
Adding @CalebProvost in assignes since yocto source code will be integrated in the Dockerfile

Method of Approach undertaken: as discussed here : https://aesd-cu-s21.slack.com/archives/C01SLFZB72Q/p1618671477027400
- Create another branch off of yocto-layer (or fork it it if you prefer)
- Create another directory for your recipe in the recipe-core directory (See https://github.com/cu-ecen-5013/final-project-CalebProvost/tree/yocto-layer/recipes-core for current example)
 - Create a recipe-name_1.0.bb within that directory (use whatever recipe version you prefer, just follow the $NAME_$VER.bb convention)
  - Add your recipe to the list of included stuff to the package on line Line 11 (for now) of conf/distro/final-project.conf
  - Push your new branch (or fork) and send a PR

**Comment by CalebProvost** [comment]
> 
> 
> Adding @CalebProvost in assignes since yocto source code is managed on the Dockerfile

It's not managed in the Dockerfile... The repo with the source code is found here:  
https://github.com/cu-ecen-5013/final-project-CalebProvost/tree/yocto-layer
The Docker container made by the Dockerfile just contains all the dependencies to make the yocto image. The `build.sh` script is what pulls and executes the build.

**Comment by arpit6232** [comment]
Successfully able to boot the image with the binaries installed in the right locations. 

Pull request under review : 
https://github.com/cu-ecen-5013/final-project-CalebProvost/pull/1

**Comment by CalebProvost** [comment]
@arpit6232 has tested his recipe with our Distro and confirms it works. I've resolved the merge conflicts and send further testing back to him.  
In addition to final confirmation that the build continues without issues after merge, @arpit6232 is additionally testing [this commit fix](https://github.com/cu-ecen-5013/final-project-CalebProvost/blob/b7b8904cc96e3ec224486e028dfc703ac8607f60/recipes-core/project-server/project-server_1.0.bb#L25-L39) for https://github.com/AESD-Course-Project/AESD-Course-Project.github.io/issues/29

**Comment by arpit6232** [comment]
Arduino-cli integrated and paths defined to work with uart-server.
