### ISSUE TITLE
Get Arduino BLE 33 demo running to install libraries and setup completely with CLI

### ISSUE THREAD

**Issue by ZachTurner07** [AESD-Course-Project/AESD-Course-Project.github.io#6]
DoD: Get demo of Arduino Nano running image detection running, and printing to the terminal

- [x] Validate camera detected by Arduino (either shield or wired) { Blocker -> Test with/without Shield }

- [x] Find source code to run on the Arduino to demo image processing {  Blocker -> Tensorflow on micro-controller  }

- [x] Test Image detection, record accuracy

**Comment by arpit6232** [comment]
Running Accuracy of 75 % currently. For more precision float values would be needed, arduino does not have an FPU. 
More optimization hangs the arduino.

Simultaneously testing to try to get a USB Camera (Webcam) started on the Jetson. 

Follow the instructions to setup the Arduino- IDE and Arduino-CLI to setup with the necessary libraries installed. 
Instructions to setup Hardware and Software here : https://github.com/AESD-Course-Project/AESD-Course-Project.github.io/blob/gh-pages/src/arduino_setup.md

**Comment by arpit6232** [comment]
DOD done.

Does not link to any specific commit. Is developed on a separate repository. And will be in the future added as a submodule.
https://github.com/arpit6232/arduino-library

![IMG_20210404_110255](https://user-images.githubusercontent.com/55374040/113534816-fef07c00-958e-11eb-98b8-305f766a2374.jpg)
![IMG_20210404_110217](https://user-images.githubusercontent.com/55374040/113534817-0152d600-958f-11eb-9e81-996687341ab8.jpg)
![IMG_20210404_105231](https://user-images.githubusercontent.com/55374040/113534821-031c9980-958f-11eb-8446-59748b6e912b.jpg)
