### ISSUE TITLE
Add Arduino IDE  functionality for firmware updates. 

### ISSUE THREAD

**Issue by CalebProvost** [AESD-Course-Project/AESD-Course-Project.github.io#9]
Include malleability to Host System's OS.
ie: Aarch64 vs $ARCH  
  
DoD: User can define environment variable to specify which architecture the host build system is.

**Comment by arpit6232** [comment]
Blocker: Setting up Arduino CLI on the docker, issues raised with connecting the Arduino IDE. 
Progress: https://hub.docker.com/repository/docker/arpit6232/arduino_cli

**Comment by arpit6232** [comment]
@CalebProvost , with the upgrades and updates over this week with the folks Arduino (https://github.com/arduino/ArduinoCore-mbed/issues/176) . We would not need the IDE anywhere. 

Do close this issue since we would not need to use change ARCH, we would simply be `wget` the necessary binaries.
